### ISSUE TITLE
I have question about the "nodeconnection.py"

### ISSUE THREAD

**Issue by WangShuoran** [macsnoeren/python-p2p-network#11]
The Event Flag is initialized in this file.
> self.terminate_flag = threading.Event()  

And it is false. This means that the thread is in a wait state.
But in run function:
> while not self.terminate_flag.is_set(): ...  

It mean the program will run when the flag is False, But in fact in this time we want it wait.
I want to say that why not `while self.terminate_flag.is_set():`.
Because it seems more common sense.

**Comment by macsnoeren** [comment]
Hi!

NodeConnection uses this event flag to determine whether it should stop. That means that when the flag is not set, the run function should run as normal. At the moment that the flasg is set, the run method should gracefully stop the thread and stop executing the NodeConnection functionality. Therefore, the while loop (which is the thread loop) has `while not self.terminate_flas.is_set()`. When the flag is not set, it should run the NodeConnection functionality.

I hope it is clear to you now.

--Maurice
