### ISSUE TITLE
I have link question between "node.py" and "nodeconnection.py"

### ISSUE THREAD

**Issue by WangShuoran** [macsnoeren/python-p2p-network#12]
Hi!

In nodeconnection.py, we have a Nodeconnection class, it has 5 parameters, respectively are main_node, sock, id, host, port.
But in node.py, "create_new_connection" method in node class has 4 parameters. And it return class that has 4 parameters.
I don't understand this behavior. Or am I missing something?

Thank you!

**Comment by WangShuoran** [comment]
Does `return NodeConnection(self, connection, id, host, port)`‘s self is corresponds to "nodeconnection.py"'s `main_node`?

**Comment by macsnoeren** [comment]
You have found it yourself ;)?

For clarification, the number of parameters is correct:
nodeconnection.py => def __init__(self, **main_node, sock, id, host, port**)
node.py => return NodeConnection(**self, connection, id, host, port**)

Indeed, self is the reference to the main_node.
