### ISSUE TITLE
Pip3 version is out of date and unstable

### ISSUE THREAD

**Issue by RyanDraves** [macsnoeren/python-p2p-network#13]
The latest version of p2pnetwork in pip3 is 0.0.3 and has at least one bug in `nodeconnection.py`. Particularly on line 54 there is a bug that has since been patched on the development and master branches `self.info = dict` -> `self.info = {}`, but a project like python-p2p-secure-node that specifies version 0.0.3 can crash when a "pong" is received.

**Comment by macsnoeren** [comment]
I will create a new update of pip from the master branch. Thanks for your remark.

**Comment by macsnoeren** [comment]
I have uploaded a new version to pip.
