### ISSUE TITLE
how

### ISSUE THREAD

**Issue by margguo** [macsnoeren/python-p2p-network#14]
`node_1.send_to_node(node_3,data="message: Hi there from 1!\n")`

**Comment by macsnoeren** [comment]
I do not understand what you want to ask. The code above is not correct and not following the decentralized application structure. A node is connected with other nodes forming a network of nodes. This can be done by connecting to other nodes or other nodes connecting with us. You can send data to your connected nodes, not to a seperate node that you have instantiated. I hope you understand. -- Maurice
