### ISSUE TITLE
how to use send_to_node api?

### ISSUE THREAD

**Issue by margguo** [macsnoeren/python-p2p-network#16]
i want to send msg to an specify node with code 

`node_1.send_to_node(node_3,data="message: Hi there from 1!\n")` ,but it not works,while send_to_nodes can works well,is there any demo show how to do?

**Comment by macsnoeren** [comment]
You need to read the documentation. I assume here that you have instantiated a node named node_1 and another node named node_3. These nodes are on its own and cannot send data to each other. Only, when these nodes are connected with each other within the network, it is possible to send data to each other. However, sending data to a specific node is not really how a decentralized network works. You could implement decentralized protocol to find a specific node within the network, connect to this node and send data. I advice to work through the examples and try to understand how decentralized networks work.

I hope you understand. If you have any questions along the why, you can ask :).

**Comment by macsnoeren** [comment]
Maybe some other thought. All functionality, like sending data to other nodes, is implemented within the node. When you instantiate a node, it is immediatly working and able to connect and recieve connections. I think that my documentation will help you to take the first step. Good luck!
