### ISSUE TITLE
Bug in connect_with_node function in node.py

### ISSUE THREAD

**Issue by richardswesterhof** [macsnoeren/python-p2p-network#25]
The `connect_with_node` function returns `None` when a connection is successfully established since there is no return statement before the end of the function in that case, however, I would expect it to return `True` to indicate that the connection was successful.

Am I misunderstanding what the return value represents (in that case an extra line elaborating on this in the function's docstring would help) or is there just a return statement missing?

**Comment by macsnoeren** [comment]
You are totally correct. The methods should improve on the return value. When a connection is created, no True is returns. I will fix this as soon as possible. Thanks for you message.

**Comment by macsnoeren** [comment]
Solved the problem, please check the updated development branch.
