### ISSUE TITLE
implementing compression to transfer large files over socket.

### ISSUE THREAD

**Issue by akasheinstein** [macsnoeren/python-p2p-network#27]
I am adding the functionality of compressing data to send and decompressing it on the other end to reduce bandwidth in the network.
help me to achieve this.
example code is here.

```
def dataencode(objectToEncode):
    data_out = jsonpickle.encode(objectToEncode, unpicklable=True)
    data_out = data_out.encode("utf-8")
    compressed_data = compress(data_out)
    return jsonpickle.encode(compressed_data, unpicklable=True)
```

**Comment by macsnoeren** [comment]
Interesting. Will have a look in the coming weeks.

**Comment by macsnoeren** [comment]
Do you have an idea or proposal to integrate it?

**Comment by akasheinstein** [comment]
yes!. I already made it work here.
but I am unable to integrate it with your code.
my working code link : https://github.com/akasheinstein/socket-communication-with-compression

**Comment by macsnoeren** [comment]
Ah, I see. I will have a look and propose a compression option in the code shortly.

**Comment by macsnoeren** [comment]
I have created a feature branch "feature_compression" in which I have started the development. So you can check it. At this moment, I am checking how to implement it within the framework without breaking current functionality. Could you give an easy example how to send and recieve compressed data? Maybe you could elaborate on how to send and recieve compressed data for the data types str, bytes and dict. That would help me a lot :).

**Comment by macsnoeren** [comment]
@akasheinstein Which compression library fo you use? I cannot find it.

**Comment by macsnoeren** [comment]
I have started the implementation with three options, namely bzip2, lzma and lzip. Current implementation not yet correct.

**Comment by macsnoeren** [comment]
@akasheinstein The compression has been implemented. Three options can be chosen, namely bzip2, lzma and zlib. Zlib has te best performance. When you send data, you are able to provide which compression you would like to add. Could you test and check it? Thanks!

**Comment by akasheinstein** [comment]
iam using zlib for compression.

**Comment by macsnoeren** [comment]
I will close the issue. If you have any questions or other things regarding compression, you can always create a new issue.
