### ISSUE TITLE
"RuntimeError: cannot join current thread" while sending a message to another node

### ISSUE THREAD

**Issue by aszokalski** [macsnoeren/python-p2p-network#3]
**What's should happen**
I need a node to send a response to another node. This is how my code looks:

```
def add_node_to_network(self, node, conn_type):
    super().connect_with_node(node.get_host(), node.get_port())
    if conn_type == 'indirect':
        super().send_to_node(node, {'type' : 'join_request_resp'})
        self.peer_book[self.UUID + 1] = node
        print("Node {} was added to the peer book".format(self.UUID+1))
        print(self.nodesIn)
        super().send_to_nodes({'type' : 'new_peer', 'node' : node, 'UUID' : self.UUID + 1})
        print("Sourcing information about new peer...")

```
**What actually happened**
I get this response
```
connect_with_node(127.0.0.1, 51687)
Node 1 was added to the peer book
[<NodeConnection(Thread-4, started 123145562787840)>]
p2p_event_node_inbound_closed: Thread-4
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Projekty/IPDS-RELATED/IPDS-Python/src/../lib/TcpServerNode.py", line 433, in run
    self.nodeServer.event_node_message(self, data)
  File "src/gateway_server.py", line 48, in event_node_message
    self.add_node_to_network(node, conn_type)
  File "src/gateway_server.py", line 63, in add_node_to_network
    super().send_to_nodes({'type' : 'new_peer', 'node' : node, 'UUID' : self.UUID + 1})
  File "/Projekty/IPDS-RELATED/IPDS-Python/src/../lib/TcpServerNode.py", line 181, in send_to_nodes
    self.send_to_node(n, data)
  File "/Projekty/IPDS-RELATED/IPDS-Python/src/../lib/TcpServerNode.py", line 192, in send_to_node
    self.delete_closed_connections()
  File "/Projekty/IPDS-RELATED/IPDS-Python/src/../lib/TcpServerNode.py", line 153, in delete_closed_connections
    n.join()
  File "/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

It seems that there is an error in the send_to_node function. I looked in your code and I didn't find anything. Maybe I'm doing something wrong.

**There's more**
There is another weird thing I noticed. I tried to use `get_port()` function you provided in your code, but it returns a different port (in my case 56310 when I specified 4560). I've tried writing the port manually in the code, but it didn't fix the issue.

PS. I see that self and super() both work. I tried both with the same effect.

**Comment by macsnoeren** [comment]
I do not understand what you are trying to do. Are you hacking the TcpServerNode.py or implementing a new node? The classes already build up a peer-to-peer network and if a node gets a request you can simply respond to it. It is a raw implementation, while you need to implement the networking packets yourself (like discovery). The best way to implement your own peer2peer node is to do the following:

`class MyNode (TcpServerNode.Node):

    # Python class constructor
    def __init__(self, host, port):
        super(MyNode, self).__init__(host, port, None)

        print("MyNode: Started")

    # Method override, implement here your own functionality
    def event_node_connected(self, node):
        print("p2p_event_node_connected: " + node.getName())

    def event_connected_with_node(self, node):
        print("p2p_event_node_connected: " + node.getName())

    def event_node_inbound_closed(self, node):
        print("p2p_event_node_inbound_closed: " + node.getName())

    def event_node_outbound_closed(self, node):
        print("p2p_event_node_outbound_closed: " + node.getName())

    # If a message comes in, determines what to do!
    def event_node_message(self, node, data):
print("p2p_event_node_message: " + node.getName() + ": " + str(data))`

The event methods you can use to communicate with the nodes that are connected. It is a true peer2peer network, so you do not have any idea how big the network is. The only way to do that is implementing a discovery function.
