### ISSUE TITLE
Length protocol instead of EOT

### ISSUE THREAD

**Issue by jordyvanraalte** [macsnoeren/python-p2p-network#30]
Hey Maurice,

Currently, I'm working on my own cryptocurrency project in Python by using a modified version of this package. Isn't a length protocol between the socket where, the first 4 bytes will be sent to determine the length of the upcoming package, then the end of transmission protocol better than the EOT protocol? If you want to send binary data to the socket isn't there a possibility that the binary contains the byte sequence EOT?

Currently, I'm implementing this in my own project however, I have not tested it fully yet.

**Comment by macsnoeren** [comment]
Hi Jordy, nice that you are interested in this framework. Feel free to use the framework which is tested. Feel also free to implement another way for communication based on length of the package. Off course you could implement some kind of protocol. However, originally this framework has been designed to communicate something like JSON. Later Samuel has added the possiblity to send dict, str and bin over the line. So, if  you would like to improve it further that would be very nice.

Furthermore, I am planning a new large update of the framework using plugins. Adding functionality and using functionality implemented by other will become much easier then.

**Comment by jordyvanraalte** [comment]
Hey Maurice,

I wanted to study how to make a Peer-To-Peer network myself based on your code, so I decided to type it over. I adjusted the code a bit for myself so that it is easier to understand. Besides that, I implemented a length protocol since I think it's better to indicate the length of a message than using a delimiter as I mentioned in my first comment and also mentioned in the official Python documentation for the socket class:

https://docs.python.org/3/howto/sockets.html

"But if you plan to reuse your socket for further transfers, you need to realize that there is no EOT on a socket. I repeat: if a socket send or recv returns after handling 0 bytes, the connection has been broken. If the connection has not been broken, you may wait on a recv forever, because the socket will not tell you that there’s nothing more to read (for now). Now if you think about that a bit, you’ll come to realize a fundamental truth of sockets: messages must either be fixed in length (yuck), be delimited (shrug), or indicate how long they are (much better), or end by shutting down the connection. The choice is entirely yours, (but some ways are righter than others)."

I am aiming to implement a blockchain myself for self-study and to provide an educational basis for my colleagues and fellow students based on Bitcoin however I'm willing to help on the open-source project.
Happy Kingsday! (sadly, we don't celebrate Kingsday here in Sweden)

**Comment by macsnoeren** [comment]
I do know that the implementation of the socket can be much better ;). It is nice to study this technology and the approach is fine off course. I was hoping on your participating to implement an improved socket communication version.

It is interesting, because the p2pnetwork aim is education as well. Students have used this framework to understand peer-to-peer and blockchain technology. It is part of the module Blockchain 1 and 2.

You need to turn Sweden orange ;). Success and maybe I will see some pull-request in the future ;).

**Comment by jordyvanraalte** [comment]
I will do a pull request after I have tested it a bit more :). If you need any help on the course, I'm willing to help as long the repositories are open source. You can reach me by email on my profile if you need to provide me with more information.

**Comment by macsnoeren** [comment]
Although I have limited time, I am aiming to create a Ethereum like blockchain in python based on this framework, https://github.com/macsnoeren/python-blockchain. That means that it is possible to also create smartcontracts and NFTs for example. This opensource project would be to educate on how smartcontracts and NFTs are implemented. Showing that the technology is very promosing. If you would like to join forces than I can help you to understand blockchain technology and we can implement an blockchain together. Just give it a thought :).

**Comment by jordyvanraalte** [comment]
Okay count me in! Will take a look later today.

**Comment by macsnoeren** [comment]
I have added this is enhancement. It would be nice if a communication protocol is implemented to create more robust communication. The send and receive functions shall still be able to send dict, str and bin. What goes in comes out at the other end. Length based, so it is easier to see when pipes are broken or any other error has occurred, Within this branch it is designed and implemented.

**Comment by jordyvanraalte** [comment]
I have added a pull request that adds the length based protocol. #32

**Comment by macsnoeren** [comment]
Thanks! I have reviewed the pull request and found some possible issues. Could you have a look? If required, we could have a chat. We can also plan a meeting, so I could give you an introduction to the blockchain technology.

**Comment by jordyvanraalte** [comment]
I looked into it and commented on it, will work on it in the beginning of June. I'm available for a meeting, mail me on ik@jordyvanraalte.nl

**Comment by macsnoeren** [comment]
Ik sluit deze ;).
