### ISSUE TITLE
Issue: unit test test_node_max_connections failed

### ISSUE THREAD

**Issue by jordyvanraalte** [macsnoeren/python-p2p-network#31]
I could not succeed the unit test test_node_max_connections. The length of the node_1_inbound is not right, seems like a bug of some sort. I have debugged the code and seems the connection is lost between node0 and node1 after sending data from the nodes. Before sending data, the inbound connections of node1 are correct. 

```python
node_0.send_to_nodes('hello from node 0')
time.sleep(2)


#place where node seems to lose it's connection
node_1.send_to_nodes('hello from node 1')
time.sleep(2)

node_2.send_to_nodes('hello from node 2')
time.sleep(2)

#test that is false.
self.assertEqual(node_1_inbound, 2, "Node 1 should have two connections from node_0 and node_2!")
```

After some deeper debugging it seems the node in send_to_node is in self.all_node however the if statement is still false.
```python
if n in self.all_nodes:
  n.send(data, compression=compression)
else:
  self.debug_print("Node send_to_node: Could not send the data, node is not found!")
```

Besides I also get the following warning however, I get this warning before the connection is lost.

```
ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 49489)>
```

I will continue debugging later this week, will let know if I find something.

**Comment by macsnoeren** [comment]
All tests are passing on my chromebook running linux. Last time I have changed to the Tox testing environment and fix the tests. Do you need to update these tests? I am also curious whether the tests are passing when you just have checked out the latest development version. 

![Screenshot 2022-05-26 23 17 03](https://user-images.githubusercontent.com/2399511/170581971-06625f4f-0c27-4651-9e1d-9b6a96071d0d.png)

**Comment by macsnoeren** [comment]
No answer received, I think it is okay.
