### ISSUE TITLE
Possible vulnerability on the node unique ID

### ISSUE THREAD

**Issue by brunoerg** [macsnoeren/python-p2p-network#4]
MD5 is used on the source code to create the node unique ID, however, md5 is a vulnerable algorithm (collision attacks). To improve the security of the protocol, I suggest to change it to a secure and efficient algorithm (Blake2, for example).

**Comment by macsnoeren** [comment]
You are correct. I do a simple ID creation and MD5 will most probably not have any collisions in this particular case. This code is used for my Blockchain course, so I will not change it now. I will consider your suggestion during the new class.

**Comment by macsnoeren** [comment]
I have changed the md5 to sha512 to create the id within the new class. So less likely to have collision attacks. Thanks for your comment.
